name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: mpossing
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile
        labels: cs598/gbert
        tags: $(git rev-parse --short "$GITHUB_SHA")
        push: ${{ github.event_name != 'pull_request' }}
