name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: mpossing
        password: ${{ secrets.DOCKER_PASS }}
  
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: |
          latest=true
        # list of Docker images to use as base name for tags
        images: |
          mpossing/cs598
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha

    - name: Build the Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
